/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 falling_leaves.glb --transform --simplify 
Files: falling_leaves.glb [3.1MB] > /Users/ph/Downloads/falling_leaves-transformed.glb [603.72KB] (81%)
Author: DogexorRexUwU (https://sketchfab.com/oscar.lopez.riviello)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/falling-leaves-d552ce56772b4ad7815ac5957bd5e104
Title: Falling Leaves
*/

import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Leaves(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/falling_leaves-transformed.glb');
	const { actions, mixer } = useAnimations(animations, group);
	useEffect(() => {
		mixer.timeScale = 0.2;
		actions.idle.play();
	}, []);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Sketchfab_Scene'>
				<primitive object={nodes.GLTF_created_0_rootJoint} />
				<skinnedMesh
					castShadow
					name='Object_30'
					geometry={nodes.Object_30.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_30.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_33'
					geometry={nodes.Object_33.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_33.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_36'
					geometry={nodes.Object_36.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_36.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_39'
					geometry={nodes.Object_39.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_39.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_42'
					geometry={nodes.Object_42.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_42.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_45'
					geometry={nodes.Object_45.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_45.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_48'
					geometry={nodes.Object_48.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_48.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_51'
					geometry={nodes.Object_51.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_51.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_54'
					geometry={nodes.Object_54.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_54.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_57'
					geometry={nodes.Object_57.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_57.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_60'
					geometry={nodes.Object_60.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_60.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_63'
					geometry={nodes.Object_63.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_63.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_66'
					geometry={nodes.Object_66.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_66.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_69'
					geometry={nodes.Object_69.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_69.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_72'
					geometry={nodes.Object_72.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_72.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_75'
					geometry={nodes.Object_75.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_75.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_78'
					geometry={nodes.Object_78.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_78.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_81'
					geometry={nodes.Object_81.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_81.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_84'
					geometry={nodes.Object_84.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_84.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_87'
					geometry={nodes.Object_87.geometry}
					material={materials.material_0}
					skeleton={nodes.Object_87.skeleton}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/falling_leaves-transformed.glb');
