/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 assignment4_flowersfbx.glb --transform --simplify 
Files: assignment4_flowersfbx.glb [8.49MB] > /Users/ph/Downloads/assignment4_flowersfbx-transformed.glb [383.7KB] (95%)
Author: Eryn_Noel (https://sketchfab.com/Eryn_Noel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/assignment4-flowersfbx-94645483db6e44819436e3a92a202efc
Title: Assignment4_FlowersFBX
*/

import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Flowers(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/assignment4_flowersfbx-transformed.glb');
	const { mixer, actions } = useAnimations(animations, group);
	useEffect(() => {
		mixer.timeScale = 2;
		actions['Take 001'].play();
	}, []);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Sketchfab_Scene'>
				<primitive object={nodes._rootJoint} />
				<mesh
					castShadow
					name='polySurface1_lambert1_0'
					geometry={nodes.polySurface1_lambert1_0.geometry}
					material={materials.lambert1}
					position={[0.606, -1.304, 0.412]}
					rotation={[-2.792, 1.154, 3.106]}
					scale={0.678}
				/>
				<skinnedMesh
					castShadow
					name='Object_7'
					geometry={nodes.Object_7.geometry}
					material={materials.lambert1}
					skeleton={nodes.Object_7.skeleton}
				/>
				<skinnedMesh
					castShadow
					name='Object_9'
					geometry={nodes.Object_9.geometry}
					material={materials.lambert1}
					skeleton={nodes.Object_9.skeleton}
				/>
			</group>
			<mesh castShadow rotation={[0, 0, -0.6]} position={[-1, -1, 1]}>
				<cylinderGeometry args={[2, 1, 6]} />
				<meshBasicMaterial color='red' />
			</mesh>
		</group>
	);
}

useGLTF.preload('/assignment4_flowersfbx-transformed.glb');
